version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: ./frontend-chisifai
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-chisifai:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - backend
    command: ["yarn", "start"]